# Generated by Django 3.2.9 on 2021-11-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0002_auto_20211116_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='max_players',
            field=models.CharField(default=4, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='organizer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='signed_players',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
