# Generated by Django 3.2.9 on 2021-11-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0003_auto_20211116_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='photo_url',
            field=models.CharField(max_length=500),
        ),
    ]
