# Generated by Django 3.2.9 on 2021-11-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0004_alter_pitch_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='place',
            new_name='pitch_id',
        ),
    ]
