# Generated by Django 3.2.9 on 2021-12-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0005_rename_place_match_pitch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickmatch.myuser'),
        ),
        migrations.AlterField(
            model_name='match',
            name='pitch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickmatch.pitch'),
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_matches',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_matches',
            field=models.ManyToManyField(blank=True, to='quickmatch.Match'),
        ),
    ]
