# Generated by Django 3.2.9 on 2021-12-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0006_auto_20211214_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='organizer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='pitch_id',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_matches',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_matches',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
