# Generated by Django 3.2.9 on 2021-12-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0007_auto_20211214_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickmatch.myuser'),
        ),
        migrations.AlterField(
            model_name='match',
            name='pitch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickmatch.pitch'),
        ),
    ]
