# Generated by Django 3.2.9 on 2021-12-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0008_auto_20211214_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='pitch_id',
            new_name='pitch',
        ),
    ]
