# Generated by Django 3.2.9 on 2021-12-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0009_rename_pitch_id_match_pitch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date', 'pitch_id'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='pitch',
            options={'ordering': ['name', 'address'], 'verbose_name': 'Pitch', 'verbose_name_plural': 'Pitches'},
        ),
    ]
