# Generated by Django 3.2.9 on 2021-12-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0011_auto_20211214_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['pitch_id'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
