# Generated by Django 3.2.9 on 2021-12-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0012_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date', 'pitch_id'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
