# Generated by Django 3.2.9 on 2021-12-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0013_alter_match_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='max_players',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='signed_players',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
