# Generated by Django 3.2.9 on 2021-12-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0014_auto_20211214_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_matches',
        ),
        migrations.AlterField(
            model_name='match',
            name='max_players',
            field=models.DecimalField(decimal_places=0, default=4, max_digits=5),
        ),
    ]
