# Generated by Django 3.2.9 on 2021-12-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0018_alter_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_matches',
            field=models.ManyToManyField(to='quickmatch.Match'),
        ),
    ]
