# Generated by Django 3.2.9 on 2022-01-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickmatch', '0024_alter_myuser_user_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='max_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='signed_players',
            field=models.IntegerField(),
        ),
    ]
